POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Joshua",
    "lastName": "Farmer",
    "age": 24,
    "emoji": "💜",
    "contactInformation": {
        "personalEmail": "joshua@iopewq.uk",
        "workEmail": "josh@bricklane-media.co.uk",
        "personalMobile": "07306022351",
        "workMobile": "07"
    },
    "currentAddress": {
        "flatNumber": "3/3",
        "buildingNumber": "82",
        "streetName": "Glasgow Road",
        "postCode": "PA1 3PN",
        "city": "Paisley",
        "county": "Renfrewshire",
        "country": "Scotlnad"
    }   
}